import { useEffect, useRef, useState } from "react";
import { ArrowRight, ArrowUpRight } from "lucide-react";

const BG_VIDEO =
  "https://grazia-prod.oss-ap-southeast-1.aliyuncs.com/resources/uid_100059067/580e1cbb-01c3-41.mov";

const HALLS = [
  {
    id: "01",
    name: "Memory Fragments",
    nameCn: "记忆碎片",
    desc: "Fragments of human memory reconstructed through AI visualization.",
    img: "https://grazia-prod.oss-ap-southeast-1.aliyuncs.com/resources/uid_100059067/museum_memory_fragments_6a6d6823.png",
  },
  {
    id: "02",
    name: "Future Origins",
    nameCn: "未来起源",
    desc: "A speculative world of emerging civilizations and synthetic ecosystems.",
    img: "https://grazia-prod.oss-ap-southeast-1.aliyuncs.com/resources/uid_100059067/museum_future_origins_47e99c77.png",
  },
  {
    id: "03",
    name: "Silent Harmony",
    nameCn: "静寂和鸣",
    desc: "A visual study of emotion, silence, and digital nature.",
    img: "https://grazia-prod.oss-ap-southeast-1.aliyuncs.com/resources/uid_100059067/museum_silent_harmony_bb678263.png",
  },
  {
    id: "04",
    name: "Neural Spaces",
    nameCn: "神经空间",
    desc: "Exploring architecture generated by neural networks.",
    img: "https://grazia-prod.oss-ap-southeast-1.aliyuncs.com/resources/uid_100059067/museum_neural_spaces_78b1a9e6.png",
  },
];

const ExhibitionHalls = () => {
  const sectionRef = useRef<HTMLDivElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const [inView, setInView] = useState(false);
  const [revealed, setRevealed] = useState(false);
  const fallbackTimerRef = useRef<number | null>(null);

  // Re-trigger every time the section enters viewport
  useEffect(() => {
    const el = sectionRef.current;
    if (!el) return;
    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting && e.intersectionRatio > 0.4) {
            setInView(true);
            setRevealed(false);
            const v = videoRef.current;
            if (v) {
              try {
                v.currentTime = 1;
              } catch {
                /* noop */
              }
              v.play().catch(() => undefined);
            }
            if (fallbackTimerRef.current) {
              window.clearTimeout(fallbackTimerRef.current);
            }
            fallbackTimerRef.current = window.setTimeout(
              () => setRevealed(true),
              5500
            );
          } else if (!e.isIntersecting) {
            // Reset when fully leaving viewport so it can replay on return
            setInView(false);
            setRevealed(false);
            const v = videoRef.current;
            if (v) {
              v.pause();
            }
            if (fallbackTimerRef.current) {
              window.clearTimeout(fallbackTimerRef.current);
              fallbackTimerRef.current = null;
            }
          }
        });
      },
      { threshold: [0, 0.4, 0.6] }
    );
    io.observe(el);
    return () => {
      io.disconnect();
      if (fallbackTimerRef.current) {
        window.clearTimeout(fallbackTimerRef.current);
      }
    };
  }, []);

  return (
    <section
      id="halls"
      ref={sectionRef}
      className="relative isolate -mt-24 overflow-hidden pt-48 pb-24 md:-mt-32 md:pt-56 md:pb-32"
    >
      {/* Background video */}
      <video
        ref={videoRef}
        src={BG_VIDEO}
        muted
        playsInline
        preload="auto"
        crossOrigin="anonymous"
        onEnded={() => setRevealed(true)}
        className={`pointer-events-none absolute inset-0 -z-10 h-full w-full object-cover transition-opacity duration-1000 ${
          inView ? "opacity-100" : "opacity-0"
        }`}
      />
      {/* Base background to avoid flash */}
      <div className="absolute inset-0 -z-20 bg-background" />

      {/* Video tint overlays — get darker once cards reveal so cards read clearly */}
      <div
        className={`pointer-events-none absolute inset-0 -z-[5] bg-background transition-opacity duration-[1400ms] ${
          revealed ? "opacity-70" : "opacity-30"
        }`}
      />
      {/* Soft top fade so the seam with the previous section melts to black */}
      <div className="pointer-events-none absolute inset-x-0 top-0 -z-[4] h-64 bg-gradient-to-b from-background via-background/80 to-transparent" />
      <div className="pointer-events-none absolute inset-x-0 bottom-0 -z-[4] h-40 bg-gradient-to-t from-background to-transparent" />

      <div className="relative mx-auto max-w-[1600px] px-6 md:px-12">
        {/* Header */}
        <div className="flex items-end justify-between gap-6">
          <div>
            <div className="flex items-center gap-3">
              <span className="h-px w-8 bg-accent" />
              <span className="eyebrow">Exhibition Halls</span>
            </div>
            <h2 className="mt-6 max-w-2xl font-display text-4xl leading-tight text-bone md:text-5xl">
              Four chambers, four ways of seeing the future.
            </h2>
          </div>
          <a
            href="#lab"
            className={`hidden items-center gap-3 self-end pb-2 transition-opacity duration-700 md:flex ${
              revealed ? "opacity-100" : "opacity-0"
            }`}
          >
            <span className="font-mono-display text-[11px] uppercase tracking-[0.3em] text-bone hover:text-accent">
              Explore All Halls
            </span>
            <ArrowRight className="h-3.5 w-3.5 text-accent" />
          </a>
        </div>

        {/* Cards — reserve final height from the start to prevent video reflow */}
        <div
          className="mt-14 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4"
          aria-hidden={!revealed}
        >
          {HALLS.map((hall, i) => (
            <article
              key={hall.id}
              className="group relative overflow-hidden rounded-sm border border-border bg-card transition will-change-transform hover:border-bone/40"
              style={{
                opacity: revealed ? 1 : 0,
                transform: revealed ? "translateY(0)" : "translateY(36px)",
                filter: revealed ? "blur(0px)" : "blur(8px)",
                transition: `opacity 900ms cubic-bezier(0.22,1,0.36,1) ${i * 160}ms, transform 900ms cubic-bezier(0.22,1,0.36,1) ${i * 160}ms, filter 900ms cubic-bezier(0.22,1,0.36,1) ${i * 160}ms`,
              }}
            >
              <div className="relative aspect-[4/5] overflow-hidden">
                <img
                  src={hall.img}
                  alt={hall.name}
                  crossOrigin="anonymous"
                  className="h-full w-full object-cover transition-transform duration-[1.4s] group-hover:scale-110"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-background via-background/40 to-background/10" />

                <div className="absolute left-4 top-4 font-mono-display text-[10px] tracking-[0.32em] text-bone/70">
                  {hall.id}
                </div>

                <div className="absolute bottom-0 left-0 right-0 p-5">
                  <h3 className="font-display text-2xl leading-tight text-bone">
                    {hall.name}
                  </h3>
                  <p className="mt-1 font-mono-display text-[10px] tracking-[0.32em] text-bone/60">
                    {hall.nameCn}
                  </p>
                  <p className="mt-3 max-h-0 overflow-hidden text-xs leading-relaxed text-muted-foreground opacity-0 transition-all duration-500 group-hover:max-h-24 group-hover:opacity-100">
                    {hall.desc}
                  </p>
                </div>

                <button className="absolute bottom-4 right-4 flex h-9 w-9 items-center justify-center rounded-full border border-bone/40 bg-background/40 text-bone backdrop-blur transition group-hover:border-accent group-hover:bg-accent group-hover:text-accent-foreground">
                  <ArrowUpRight className="h-3.5 w-3.5" />
                </button>
              </div>
            </article>
          ))}
        </div>

        {/* Subtle hint while video plays — absolute so it never affects layout */}
        <div
          className={`pointer-events-none absolute left-6 bottom-6 flex items-center gap-3 text-bone/70 transition-opacity duration-700 md:left-12 md:bottom-10 ${
            inView && !revealed ? "opacity-100" : "opacity-0"
          }`}
        >
          <span className="h-px w-10 bg-bone/40" />
          <span className="font-mono-display text-[10px] uppercase tracking-[0.32em]">
            Awakening the halls…
          </span>
        </div>
      </div>
    </section>
  );
};

export default ExhibitionHalls;
